import { passkeyClient } from "@better-auth/passkey/client"
import { createAuthClient } from "better-auth/svelte"

// assumes the same domain for server and client application
// as well as /api/auth base path for authentication purposes (auto-generated by better-auth)
export const authClient = createAuthClient({
    plugins: [
        passkeyClient()
    ]
})

export const { signIn, signUp, useSession } = authClient;